expose:
- desc: monitor the container
  name: monitor
  outPort: 38080
  protocolPort: http://:8080
funcs:
- devices:
  - deviceName: "三厂-pyboot测试设备1"
    deviceAttr:
    - attrExpression: == data_to_dict['deviceInfo']['deviceName']
      attrName: deviceName
      attrValue: 三厂-pyboot测试设备1
    - attrExpression: in data_to_dict['telemetry']
      attrName: pointName
      attrValue: pyboot1
  modelAmd64Address: http://192.168.241.1:8080/Ch1hQGGkxnSAIiFrAAO8COz2yGE652.zip
  modelName: multivariate
- devices:
  - deviceName: "三厂-pyboot测试设备1"
    deviceAttr:
    - attrExpression: == data_to_dict['deviceInfo']['deviceName']
      attrName: deviceName
      attrValue: 设备3
    - attrExpression: in data_to_dict['telemetry']
      attrName: pointName
      attrValue: RC_cylinder1_1P_d_dispPeak
  modelAmd64Address: http://192.168.241.1:8080/trend_detection.zip
  modelName: trend_detection
mqtts:
- broker: tcp://192.168.241.1:1883
  name: mosquitto-20336454-5413-4e2f-b52e-b945291359c7
  retain: false
rules:
- pub:
    clientId: ef2712a2-926d-4388-92d0-60470ab2613d
    name: mosquitto-20336454-5413-4e2f-b52e-b945291359c7
    timeout: 100
    topic: cloud/edge-pyboot-e060ff31-1644570929743-e54d4620-8b1a-11ec-9969-df2a36238047
  sub:
    clientId: ae03af75-13f5-4cf9-9145-0fea4e6ff1e4
    name: mosquitto-20336454-5413-4e2f-b52e-b945291359c7
    topic: cloud/edge-data-access-a60c2306-1644570929743-e54d4620-8b1a-11ec-9969-df2a36238047
