#FROM --platform=$TARGETPLATFORM python:3-slim-buster
#FROM python:3.6-slim
FROM --platform=$TARGETPLATFORM python:3.9.16 as builder

RUN set -eux && sed -i "s/deb.debian.org/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
RUN sed -i "s/security.debian.org/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
RUN apt-get update && apt-get install libgomp1 telnet dnsutils unzip -y
RUN apt-get install gfortran -y
RUN apt-get install gcc-9 -y
RUN apt-get install gfortran-9 -y
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 40
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
RUN update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-10 40
RUN update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-9 100
RUN apt-get install libopenblas-dev liblapack-dev libatlas-base-dev libblas-dev -y

COPY ./_build/requirements.txt /home
COPY ./_build/numpy-1.17.4.zip /tmp
COPY ./_build/scipy-1.4.0.tar.gz /tmp
COPY ./_build/scikit-image-0.16.2.tar.gz /tmp
RUN mkdir ~/.pip
RUN echo "[global]\nindex-url = https://pypi.tuna.tsinghua.edu.cn/simple\n[install]\ntrusted-host = https://pypi.tuna.tsinghua.edu.cn\n[list]\nformat = columns" > ~/.pip/pip.conf
RUN python -m pip install --upgrade pip
RUN unzip /tmp/numpy-1.17.4.zip -d /tmp
RUN tar -zxvf /tmp/scipy-1.4.0.tar.gz -C /tmp
RUN tar -zxvf /tmp/scikit-image-0.16.2.tar.gz -C /tmp
WORKDIR /tmp/numpy-1.17.4
RUN python setup.py install
WORKDIR /tmp/scipy-1.4.0
RUN python setup.py install
RUN pip install PyWavelets~=1.1.1
RUN pip install imageio~=2.13.5
RUN pip install networkx~=2.5.1
RUN apt-get install g++ -y
RUN apt-get install g++-9 -y
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 40
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
RUN pip install matplotlib~=3.3.4
COPY ./_build/packaging-21.3.tar.gz /tmp
RUN tar -zxvf /tmp/packaging-21.3.tar.gz -C /tmp
WORKDIR /tmp/packaging-21.3
RUN python setup.py install
WORKDIR /tmp/scikit-image-0.16.2
RUN python setup.py install
COPY ./_build/scikit-learn-0.20.4.tar.gz /tmp
RUN tar -zxvf /tmp/scikit-learn-0.20.4.tar.gz -C /tmp
WORKDIR /tmp/scikit-learn-0.20.4
RUN python setup.py install
COPY ./_build/requirements-arm.txt /home
RUN apt-get install cmake -y
RUN pip install -r /home/requirements-arm.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/


# ENV PYTHONPATH "/home/work"

# WORKDIR /home/work
# COPY ./pyboot /home/work/pyboot

# ENTRYPOINT ["python", "pyboot/brun/main.py"]

FROM --platform=$TARGETPLATFORM python:3.9.16
RUN set -eux && sed -i "s/deb.debian.org/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
RUN sed -i "s/security.debian.org/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
RUN apt-get update && apt-get install libgomp1 telnet dnsutils unzip -y

RUN apt-get install libopenblas-dev liblapack-dev libatlas-base-dev libblas-dev -y
RUN mkdir ~/.pip
RUN echo "[global]\nindex-url = https://pypi.tuna.tsinghua.edu.cn/simple\n[install]\ntrusted-host = https://pypi.tuna.tsinghua.edu.cn\n[list]\nformat = columns" > ~/.pip/pip.conf
RUN python -m pip install --upgrade pip

COPY --from=builder /usr/local/bin /usr/local/bin
COPY --from=builder /usr/local/lib/python3.9/site-packages /usr/local/lib/python3.9/site-packages

ENV PYTHONPATH "/home/work"
WORKDIR /home/work
COPY ./pyboot /home/work/pyboot

ENTRYPOINT ["python", "pyboot/brun/main.py"]
